# Generated by Django 5.0.3 on 2024-05-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
