# Generated by Django 5.0.3 on 2024-05-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(default='Is a room'),
        ),
    ]
