# Generated by Django 5.0.3 on 2024-05-29 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0002_useractivity_userstreak'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
