# Generated by Django 5.0.3 on 2024-06-12 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0004_sessiongoal_timeraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeraction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userstreak',
            name='user',
        ),
        migrations.DeleteModel(
            name='SessionGoal',
        ),
        migrations.DeleteModel(
            name='TimerAction',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
        migrations.DeleteModel(
            name='UserStreak',
        ),
    ]
